# basic options
title: Contact Information
author: Allen Liu
email: liuallen2@gmail.com
description: My website
facebook_username: jekyllrb
github_username:  Allen589

# Build settings
markdown: kramdown
theme: minima
